import streamlit as st
import requests

API_URL = "https://TokenTutor-Grade5MathBackend.hf.space/MathQuestion"

st.set_page_config(
    page_title="5th Grade Math Tutor",
    page_icon="📘",
    layout="centered"
)

st.title("📘 5th Grade Math Tutor")
st.caption("Ask a math question or request practice problems")

with st.expander(" Disclaimer", expanded=False):
    st.markdown("""
    - This tool supports learning aligned with the **TEKS Grade 5 Mathematics** curriculum.
    - Content is generated by an AI model and **may not always be correct**.
    - **Adult supervision is recommended** when children use this tool.
    - The generator may hallucinate, meaning some answers or explanations could be inaccurate.
    - This tool **does not remember previous questions or conversations**. Each request is handled independently.
    - This tool should **not be used for graded assignments or exams**.
    - Users should verify answers using textbooks or guidance from teachers.
    - Do **not share personal or sensitive information**.
    """)

# -------------------------
# Session State
# -------------------------
if "chat" not in st.session_state:
    st.session_state.chat = []

# -------------------------
# Render Chat History
# -------------------------
for msg in st.session_state.chat:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# -------------------------
# User Input
# -------------------------
user_input = st.chat_input("Type your math question here...")

if user_input:
    # User message
    st.session_state.chat.append({
        "role": "user",
        "content": user_input
    })
    with st.chat_message("user"):
        st.markdown(user_input)

    # -------------------------
    # Call Backend
    # -------------------------
    try:
        response = requests.post(
            API_URL,
            json={"query": user_input},
            timeout=30
        )
        response.raise_for_status()
        data = response.json()

        ai_message = ""

        # -------------------------
        # Concept
        # -------------------------
        if data["type"] == "Concept":
            ai_message = f"📘 **Explanation**\n\n{data['message']}"

        # -------------------------
        # Questions
        # -------------------------
        elif data["type"] == "Questions":
            ai_message = "🧮 **Practice Questions**\n\n"

            for idx, q in enumerate(data["message"], start=1):

                # Safely extract question text
                question_text = q.get("Question")

                if not question_text:
                    for k in q.keys():
                        if k.lower().startswith("q"):
                            question_text = q[k]
                            break

                if not question_text:
                    question_text = "Question text not available."

                ai_message += f"**Q{idx}. {question_text}**\n\n"

                for opt_key, opt_value in q["Answers"].items():
                    ai_message += f"- **{opt_key}.** {opt_value}\n"

                ai_message += (
                    f"\n✅ **Correct Option:** {q['CorrectOption']}\n"
                    f"✅ **Correct Answer:** {q['CorrectAnswer']}\n\n"
                    "---\n\n"
                )

        # -------------------------
        # Refusal
        # -------------------------
        elif data["type"] == "Refusal":
            ai_message = f"⚠️ {data['message']}"

        else:
            ai_message = "⚠️ Unexpected response from server."

    except Exception as e:
        ai_message = f"❌ Error connecting to backend:\n{e}"

    # Assistant message
    st.session_state.chat.append({
        "role": "assistant",
        "content": ai_message
    })

    with st.chat_message("assistant"):
        st.markdown(ai_message)

